version: '3.8'

services:
  app:
    image: php:8.1-fpm
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini # Opcional: personaliza configuraciones de PHP
    networks:
      - laravel
    command: >
      sh -c "apt-get update &&
             apt-get install -y libpng-dev libonig-dev libxml2-dev zip unzip git curl &&
             docker-php-ext-install pdo_mysql &&
             php-fpm"
  
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: gi2025* 
      MYSQL_DATABASE: gi           
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel: